apiVersion: v1
kind: Service
metadata:
  name: teleport-postgres
  namespace: teleport-databases
spec:
  clusterIP: None
  selector:
    app: teleport-postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
