apiVersion: resources.teleport.dev/v1
kind: TeleportRoleV8
metadata:
  name: okta-base-requester
  namespace: teleport
spec:
  allow:
    request:
      roles:
        - okta-kube-access
        - okta-ssh-access
        - okta-ssh-root
      # reason set to ensure audit event recorded for auto-approval
      reason:
        mode: "required"
        prompt: "Justification (ticket ID, etc.)"
      thresholds:
        - approve: 1
          deny: 1
      max_duration: 8h
  options:
    max_session_ttl: 12h