apiVersion: resources.teleport.dev/v1
kind: TeleportRoleV8
metadata:
  name: okta-ssh-access
  namespace: teleport
spec:
  allow:
    logins: ["{{email.local(external.username)}}"]
    node_labels:
      aws/env: ["dev"]
  options:
    create_host_user_mode: keep
    create_host_user_default_shell: /bin/bash
    max_session_ttl: 4h