# GitHub App credentials for the notification Provider
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: flux-github-app
  namespace: flux-system
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secrets-manager
  target:
    name: flux-github-app
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: ${SECRET_PREFIX}/flux-github-app
---
# GitHub App credentials for the githubdispatch Provider
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: flux-github-dispatch-app
  namespace: flux-system
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secrets-manager
  target:
    name: flux-github-dispatch-app
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: ${SECRET_PREFIX}/flux-github-dispatch-app
