apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: teleport
resources:
  - auto-approve-okta-ssh-access.yaml
labels:
  - includeSelectors: false
    pairs:
      app.kubernetes.io/part-of: teleport
      teleport.dev/managed-by: flux
