# Postgres PKI + Teleport's client certificate.
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-pki
  namespace: flux-system
spec:
  dependsOn:
    - name: infra-controllers
  interval: 30m
  retryInterval: 1m
  timeout: 10m
  path: ./infrastructure/pki
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
    - apiVersion: cert-manager.io/v1
      kind: Certificate
      name: teleport-backend-client
      namespace: teleport
    - apiVersion: cert-manager.io/v1
      kind: Certificate
      name: teleport-postgres-server
      namespace: teleport-databases
