apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: teleport
resources:
  - helmrelease.yaml

configMapGenerator:
  - name: teleport-cluster-values
    files:
      - values.yaml

generatorOptions:
  # disabled because Kustomize doesn't rewrite HelmRelease.spec.valuesFrom name references
  # if enabled, Flux will look for a ConfigMap that Kustomize configMapGenerator renamed and throw a "not found" error
  disableNameSuffixHash: true
