# CA that signs Teleport's client cert to connect to Postgres
apiVersion: trust-manager.io/v1alpha2
kind: ClusterBundle
metadata:
  name: teleport-db-client-ca
spec:
  sourceRefs:
    - kind: Secret
      name: postgres-client-ca-key-pair
      key: tls.crt
  target:
    configMap:
      data:
        - key: db-client.cas
    namespaceSelector:
      matchLabels:
        kubernetes.io/metadata.name: teleport-databases
