apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - postgres-ca.yaml
  - postgres-client-ca.yaml
  - teleport-backend-client.yaml
  - db-client-ca-clusterbundle.yaml
  - server-ca-clusterbundle.yaml
