apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: teleport-license
  namespace: teleport
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secrets-manager
  target:
    name: license
    creationPolicy: Owner
  data:
    - secretKey: license.pem
      remoteRef:
        key: ${SECRET_PREFIX}/enterprise-license
        property: license.pem